import React from 'react'

export function ImagePlaceholderGifPattern() {
  const basePath = '/img/patterns'
  const patternFiles = [
    "acer.gif",
    "anchors.gif",
    "antionette.gif",
    "armada.gif",
    "autumn-butterflies.gif",
    "battle-royale.gif",
    "beachy.gif",
    "bewitched.gif",
    "bit-tile-blue.gif",
    "brooks.gif",
    "camellia.gif",
    "cellar-heat.gif",
    "dead-kings.gif",
    "dharma-initiative-jungle.gif",
    "flowerBurst.gif",
    "fronds.gif",
    "frost-variant.gif",
    "frost.gif",
    "green-hawaii.gif",
    "haunted-red.gif",
    "hold-fast.gif",
    "hot-pink-damask.gif",
    "indian-summer.gif",
    "intertwined.gif",
    "intrigue.gif",
    "iridescent.gif",
    "irish.gif",
    "medallion-burned.gif",
    "medallion-tightened-blue.gif",
    "medusa-chandelier.gif",
    "palmetto.gif",
    "peach-swirl.gif",
    "plum.gif",
    "prim-walls.gif",
    "pumpkin.gif",
    "queen-lime-carpet-sample.gif",
    "relic-jungle.gif",
    "relic-xmas-paper.gif",
    "relic.gif",
    "ripple.gif",
    "risen.gif",
    "royals.gif",
    "sanskrit.gif",
    "sapphire.gif",
    "sea-scope.gif",
    "shanghai.gif",
    "simple-paisley.gif",
    "something-70s-bright.gif",
    "starliner.gif",
    "steadfast.gif",
    "straw-flowers.gif",
    "sunrise.gif",
    "transmit.gif",
    "tutorial.gif",
    "urban-royalty.gif",
    "vintage-scarlet.gif",
    "violet.gif",
  ]
  const chosenPattern = patternFiles[Math.floor(Math.random() * patternFiles.length)]
  const patternURL = `${basePath}/${chosenPattern}`
  return <div className="image-placeholder" style={{ backgroundImage: `url(${patternURL})` }}><div></div></div>
}
